---
- name: Ensure /etc/ansible directory exists.
  file:
    path: /etc/ansible
    state: directory
  become: yes

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
  become: true

- name: Add sudoers users to wheel group
  user: name=jenkins groups=wheel append=yes state=present createhome=yes
  become: true