---
- name: Check if RVM already Installed
  stat: path=~/.rvm/
  register: rvm_dir

- name: Install GPG key for RVM
  shell: curl -sSL https://rvm.io/mpapis.asc | /usr/local/bin/gpg --import -
  when: rvm_dir.stat.exists == False
  become_user: jenkins

- name: Install RVM for the user
  shell: curl -sSL https://get.rvm.io | bash -s stable --ruby
  when: rvm_dir.stat.exists == False
  become_user: jenkins

- name: Add RVM to the users bash profile
  command: echo "source $HOME/.rvm/scripts/rvm" >> ~/.bash_profile
  when: rvm_dir.stat.exists == False
  become_user: jenkins

- name: Install ruby version
  shell: bash -l -c "~/.rvm/bin/rvm install {{ ruby_version }}"
  when: rvm_dir.stat.exists == False
  become_user: jenkins

- name: Set Ruby Default
  shell: bash -l -c "~/.rvm/bin/rvm default {{ ruby_version }}"
  when: rvm_dir.stat.exists == False
  become_user: jenkins

- name: Setup Installed Ruby
  shell: rvm default {{ ruby_version }} >> ~/.bash_profile
  when: rvm_dir.stat.exists == False
  become_user: jenkins

- name: Install Ruby Gems required for iOS app developement
  gem: name={{item}} state=latest
  with_items: "{{ rubygems_packages_to_install }}"
  when: rvm_dir.stat.exists == False
  become_user: jenkins
